// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file message.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file message.proto.
 */
export const file_message: GenFile = /*@__PURE__*/
  fileDesc("Cg1tZXNzYWdlLnByb3RvIlUKDlN0dWRlbnRDaGVja0luEhIKCnN0dWRlbnRfaWQYASABKAkSEQoJdGltZXN0YW1wGAIgASgDEg4KBmFjdGlvbhgDIAEoCRIMCgRyc3NpGAQgASgFIjYKDFNlc3Npb25SZXNldBIVCg1zZXNzaW9uX3N0YXJ0GAEgASgDEg8KB3Jvb21faWQYAiABKAkiUAoRQXR0ZW5kYW5jZVN1Y2Nlc3MSEgoKc3R1ZGVudF9pZBgBIAEoCRIUCgxzdHVkZW50X25hbWUYAiABKAkSEQoJdGltZXN0YW1wGAMgASgDYgZwcm90bzM");

/**
 * Sent by the student app -> server -> ESP32 receives confirmation
 *
 * @generated from message StudentCheckIn
 */
export type StudentCheckIn = Message<"StudentCheckIn"> & {
  /**
   * @generated from field: string student_id = 1;
   */
  studentId: string;

  /**
   * @generated from field: int64 timestamp = 2;
   */
  timestamp: bigint;

  /**
   * @generated from field: string action = 3;
   */
  action: string;

  /**
   * @generated from field: int32 rssi = 4;
   */
  rssi: number;
};

/**
 * Describes the message StudentCheckIn.
 * Use `create(StudentCheckInSchema)` to create a new message.
 */
export const StudentCheckInSchema: GenMessage<StudentCheckIn> = /*@__PURE__*/
  messageDesc(file_message, 0);

/**
 * Published by server to attendance/room-101/reset
 * Signals the start of a new attendance session
 *
 * @generated from message SessionReset
 */
export type SessionReset = Message<"SessionReset"> & {
  /**
   * @generated from field: int64 session_start = 1;
   */
  sessionStart: bigint;

  /**
   * @generated from field: string room_id = 2;
   */
  roomId: string;
};

/**
 * Describes the message SessionReset.
 * Use `create(SessionResetSchema)` to create a new message.
 */
export const SessionResetSchema: GenMessage<SessionReset> = /*@__PURE__*/
  messageDesc(file_message, 1);

/**
 * Published by server to attendance/room-101/success
 * Confirms a student has successfully checked in
 *
 * @generated from message AttendanceSuccess
 */
export type AttendanceSuccess = Message<"AttendanceSuccess"> & {
  /**
   * @generated from field: string student_id = 1;
   */
  studentId: string;

  /**
   * @generated from field: string student_name = 2;
   */
  studentName: string;

  /**
   * @generated from field: int64 timestamp = 3;
   */
  timestamp: bigint;
};

/**
 * Describes the message AttendanceSuccess.
 * Use `create(AttendanceSuccessSchema)` to create a new message.
 */
export const AttendanceSuccessSchema: GenMessage<AttendanceSuccess> = /*@__PURE__*/
  messageDesc(file_message, 2);

