// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file message.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file message.proto.
 */
export const file_message: GenFile = /*@__PURE__*/
  fileDesc("Cg1tZXNzYWdlLnByb3RvIiUKDFNlc3Npb25TdGFydBIVCg1zZXNzaW9uX3N0YXJ0GAEgASgDIgwKClNlc3Npb25FbmQiUAoRQXR0ZW5kYW5jZVN1Y2Nlc3MSEgoKc3R1ZGVudF9pZBgBIAEoCRIUCgxzdHVkZW50X25hbWUYAiABKAkSEQoJdGltZXN0YW1wGAMgASgDYgZwcm90bzM");

/**
 * Published by server to classroom/{room_uuid}/start-session
 * Signals the start of a new attendance session
 *
 * @generated from message SessionStart
 */
export type SessionStart = Message<"SessionStart"> & {
  /**
   * @generated from field: int64 session_start = 1;
   */
  sessionStart: bigint;
};

/**
 * Describes the message SessionStart.
 * Use `create(SessionStartSchema)` to create a new message.
 */
export const SessionStartSchema: GenMessage<SessionStart> = /*@__PURE__*/
  messageDesc(file_message, 0);

/**
 * Published by server to classroom/{room_uuid}/end-session
 * Signals the end of an attendance session
 *
 * @generated from message SessionEnd
 */
export type SessionEnd = Message<"SessionEnd"> & {
};

/**
 * Describes the message SessionEnd.
 * Use `create(SessionEndSchema)` to create a new message.
 */
export const SessionEndSchema: GenMessage<SessionEnd> = /*@__PURE__*/
  messageDesc(file_message, 1);

/**
 * Published by server to classroom/{room_uuid}/attendance
 * Confirms a student has successfully checked in
 *
 * @generated from message AttendanceSuccess
 */
export type AttendanceSuccess = Message<"AttendanceSuccess"> & {
  /**
   * @generated from field: string student_id = 1;
   */
  studentId: string;

  /**
   * @generated from field: string student_name = 2;
   */
  studentName: string;

  /**
   * @generated from field: int64 timestamp = 3;
   */
  timestamp: bigint;
};

/**
 * Describes the message AttendanceSuccess.
 * Use `create(AttendanceSuccessSchema)` to create a new message.
 */
export const AttendanceSuccessSchema: GenMessage<AttendanceSuccess> = /*@__PURE__*/
  messageDesc(file_message, 2);

